### PR TITLE
[WIP] add json schema

### PR DESCRIPTION
**Pull request by corburn**
Following up on #5, this change introduces a draft BCO JSON schema.

- [x] Use [HCV1a.json](https://github.com/biocompute-objects/BCO_Specification/blob/cb06839d482b4b645eadf9160c48cb8a2162475f/HCV1a.json) to generate an initial draft with https://www.jsonschema.net
- [x] Resolve inconsistencies with [base_type_BioCompute.json](https://github.com/biocompute-objects/BCO_Specification/blob/cb06839d482b4b645eadf9160c48cb8a2162475f/base_type_BioCompute.json)
- [ ] Resolve inconsistencies with *.md file
- [ ] Review, in particular, the following nebulous domains: error_domain, extensions_domain, io_domain, and parameters_domain

The following script was used to test the schema against [HCV1a.json](https://github.com/biocompute-objects/BCO_Specification/blob/cb06839d482b4b645eadf9160c48cb8a2162475f/HCV1a.json):

```python
import json
import jsonref
import os
import sys

from jsonschema import validate

def main():
    import argparse
    parser = argparse.ArgumentParser()
    parser.add_argument('json', type=argparse.FileType('r'), help="json to validate")
    parser.add_argument('schema', type=argparse.FileType('r'), help="root json schema to validate against")
    args = parser.parse_args()

    base_uri = 'file://{}/'.format(os.path.dirname(args.schema.name))

    data = json.load(args.json)
    schema = jsonref.load(args.schema, base_uri=base_uri, jsonschema=True)

    return validate(data, schema)

if __name__ == "__main__":
    main()
```
The following commands were used to run the script:
```bash
cd BCO_specification/
python -m venv env
source env/bin/activate
pip install jsonschema jsonref
python validate.py HCV1a.json $PWD/schemas/biocomputeobject.json
```

---

- [ ] Should URI fields be validated as IRI?
       https://tools.ietf.org/html/rfc3987
- [ ] How should *_extension fields be handled?
       http://json-schema.org/draft-06/json-schema-release-notes.html#q-what-happened-to-all-the-discussions-around-re-using-schemas-with-additionalproperties

The following definition for `extension_domain` failed to trigger validation errors when tested with the above jsonschema script. It may be the library doesn't support it (propertyNames test cases are sparse) or the definition is invalid.

```json
"extension_domain": {
  "type": "object",
  "propertyNames": {
    "$comment": "Need to 'anyOf' these or else the enum and pattern conflict",
    "$comment": "https://github.com/json-schema-org/json-schema-spec/issues/214#issue-197927069",
    "anyOf": [
      {"enum": ["fhir_extension", "github_extension"]},
      {"pattern": "*_extension"}
    ]
  }
},
```

### CODE REVIEW

**Comment by corburn** [comment]
@stain do you have recommendations for how to implement the `extension_domain`?

Currently I'm looking at [`propertyNames`](http://json-schema.org/draft-06/json-schema-release-notes.html#q-what-happened-to-all-the-discussions-around-re-using-schemas-with-additionalproperties) and haven't yet looked into the [Hyper Schema](https://datatracker.ietf.org/doc/draft-handrews-json-schema-hyperschema/) or [relative JSON pointers](https://datatracker.ietf.org/doc/draft-handrews-relative-json-pointer/).

**Comment by mr-c** [comment]
Here is a visualization of the schema so far
screenshot from 2018-11-16 10-31-55

**Comment by corburn** [comment]
screen shot 2018-11-16 at 10 21 26 am

**Comment by HadleyKing** [comment]
@corburn How long would it take you to finish a version of the schema with out waiting for all of the discussion issues to be resolved?
@rykahsay would like to implement a BCO tool he has started based on your schema work already but he does not want to replicate work or go in a different direction. He suggested that we define the remaining domains using what is in the spec to get his the tool working (which he will put in a repo here once it is done).

**Comment by corburn** [comment]
@HadleyKing the schema is current to the extent I can make it at this time.

**Comment by mr-c** [comment]
@corburn @HadleyKing Shall we transfer the remaining unchecked boxes to separate issues so they don't get lost?

**Pull request merged**
